steps:
  load_data:
    enable_cache: False
    parameters:
      data_version: "4032f4b5a53ede38e9543fc57b5f7fba42bdb216"
      data_postfix: "raw"
      reference_data_version: "4032f4b5a53ede38e9543fc57b5f7fba42bdb216"
  clean_data:
    enable_cache: False
  validate_data:
    enable_cache: False
  version_data:
    enable_cache: False
    parameters:
      data_version_name: "second_version"
      filename_roots: ["mind_data_validated", "nhs_data_validated"]
      debug_mode: True
